{
 "title": "wartezeiten.app",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "selectPark",
    "label": "Select Park",
    "query": {
     "query": "from(bucket: \"wartezeiten\")\r\n  |> range(start: -30d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"waiting_times\")\r\n  |> keep(columns: [\"park_name\"])\r\n  |> group()\r\n  |> distinct(column: \"park_name\")\r\n  |> sort()\r\n"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Wartezeiten",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "query": "from(bucket: \"wartezeiten\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"park_name\"] == \"${selectPark}\") \r\n  |> filter(fn: (r) => r[\"_field\"] == \"waiting_time\")\r\n  |> map(fn: (r) => ({\r\n        _time: r._time,\r\n        _value: r._value,\r\n        _field: r.attraction,   // Legende = Ride-Name\r\n        _measurement: \"rides\"   // optional, einheitliches Measurement\r\n    }))\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\", \"_measurement\"])\r\n"
    }
   ]
  },
  {
   "title": "Wartezeiten",
   "type": "table",
   "gridPos": { "h": 18, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "query": "from(bucket: \"wartezeiten\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"park_name\"] == \"${selectPark}\") \r\n  |> filter(fn: (r) => r[\"_field\"] == \"waiting_time\")\r\n  |> filter(fn: (r) => r._value >= 15)           // nur Wartezeiten >= 15 min\r\n  |> last()                                      // nur letzter Wert pro Ride\r\n  |> map(fn: (r) => ({\r\n        _time: r._time,\r\n        Zeit: r._value,     // neues Feld\r\n        Ride: r.attraction,      // Ride-Name umbenannt\r\n        _measurement: \"rides\"\r\n    }))\r\n  |> keep(columns: [\"_time\", \"Zeit\", \"Ride\"])\r\n"
    }
   ]
  },
  {
   "title": "Park Status",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 6, "x": 16, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"wartezeiten\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"opening_times\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"opened_today\")\r\n  |> map(fn: (r) => ({\r\n        _time: r._time,\r\n        _value: r._value,        // true/false\r\n        _field: r.park_name,     // Parkname als Legende\r\n        _measurement: \"\"         // Measurement leer, verhindert doppelte Anzeige\r\n    }))\r\n"
    }
   ]
  },
  {
   "title": "Ride Status",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 6, "x": 16, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"wartezeiten\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"waiting_times\")\r\n  |> filter(fn: (r) => r[\"park_name\"] == \"${selectPark}\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"waiting_time\")   // nur um die Zeilen zu bekommen\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({\r\n        _time: r._time,\r\n        _value: r.status,      // Status als String behalten\r\n        _field: r.attraction   // Ride-Name für Legende\r\n    }))\r\n  |> yield(name: \"status_timeline\")\r\n"
    }
   ]
  }
 ]
}